### ISSUE TITLE
Running `npm install` twice fails ("unknown error, lstat")

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#664]
Originally discussed [here](https://github.com/Esri/arcgis-rest-js/issues/40#issuecomment-502819331). - I suspect this only happens on Windows 10?

## Replication steps:
1. Clone repo
2. run `npm install`
3. run `npm install` again
  - Expected: Running `npm install` again runs without issues
  - Actual: `Error: UNKNOWN: unknown error, lstat 'C:\...\arcgis-rest-js\packages\arcgis-rest-auth\node_modules\@esri\arcgis-rest-request'` (full error message below)

## Full Error Message
```
PS C:\...\arcgis-rest-js> npm install

> @esri/arcgis-rest-js@2.9.0 postinstall C:\...\arcgis-rest-js
> npm run bootstrap


> @esri/arcgis-rest-js@2.9.0 bootstrap C:\...\arcgis-rest-js
> lerna bootstrap

lerna info version 2.11.0
lerna info Bootstrapping 22 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
fs.js:114
    throw err;
    ^

Error: UNKNOWN: unknown error, lstat 'C:\...\arcgis-rest-js\packages\arcgis-rest-auth\node_modules\@esri\arcgis-rest-request'
    at Object.lstatSync (fs.js:845:3)
    at Object.lstatSync (C:\...\arcgis-rest-js\node_modules\graceful-fs\polyfills.js:308:16)
    at resolveSymbolicLink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:223:33)
    at resolveWindowsSymlink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:240:31)
    at Function.isSymlink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:178:18)
    at C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:410:62
    at Array.reduce (<anonymous>)
    at C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:403:54
    at Array.map (<anonymous>)
    at Function.symlinkPackages (C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:393:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @esri/arcgis-rest-js@2.9.0 bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @esri/arcgis-rest-js@2.9.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-03-03T18_31_25_187Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @esri/arcgis-rest-js@2.9.0 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @esri/arcgis-rest-js@2.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-03-03T18_31_25_292Z-debug.log
```

## Env

- NPM: `v6.9.0`
- Node: `v10.16.3`
- OS: Windows 10, version `1709`

## Possible Workaround

[Manually delete the `node_modules` under `packages/arcgis-rest-request/` before running `npm i`](https://github.com/Esri/arcgis-rest-js/issues/40#issuecomment-502819331) allows the `npm install` to appear to work, but we still get that same error as part of the process (see below) which I believe prevents downstream actions like building and testing to work, so I do not think this is a valid workaround.

```
> lerna bootstrap

lerna info version 2.11.0
lerna info Bootstrapping 22 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
(node:22872) UnhandledPromiseRejectionWarning: Error: UNKNOWN: unknown error, lstat 'C:\...\arcgis-rest-js\packages\arcgis-rest-auth\node_modules\@esri\arcgis-rest-request'
    at Object.lstatSync (fs.js:845:3)
    at Object.lstatSync (C:\...\arcgis-rest-js\node_modules\graceful-fs\polyfills.js:308:16)
    at resolveSymbolicLink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:223:33)
    at resolveWindowsSymlink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:240:31)
    at Function.isSymlink (C:\...\arcgis-rest-js\node_modules\lerna\lib\FileSystemUtilities.js:178:18)
    at C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:410:62
    at Array.reduce (<anonymous>)
    at C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:403:54
    at Array.map (<anonymous>)
    at Function.symlinkPackages (C:\...\arcgis-rest-js\node_modules\lerna\lib\PackageUtilities.js:393:30)
(node:22872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gavinr** [comment]
I get the same issue when running `npm run bootstrap` - so I guess this issue is specifically related to running `lerna bootstrap`, which `npm install` does as part of the `postinstall`.

**Comment by gavinr** [comment]
This issue does not happen for me anymore. Closing.
